# Generated by Django 4.0.5 on 2022-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('tweet_text', models.CharField(max_length=200)),
                ('tweet_rts', models.IntegerField()),
                ('tweet_likes', models.IntegerField()),
                ('tweet_replies', models.IntegerField()),
            ],
        ),
    ]
