# Generated by Django 4.0.5 on 2022-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_tweet_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.TextField(max_length=200),
        ),
    ]
