# Generated by Django 4.0.5 on 2022-06-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_tweet_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_likes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_replies',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_rts',
            field=models.PositiveIntegerField(),
        ),
    ]
