# Generated by Django 4.0.6 on 2022-07-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_tweet_tweet_likes_alter_tweet_tweet_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_author',
            field=models.CharField(default='SkySportsNews', max_length=50),
            preserve_default=False,
        ),
    ]
